common:
  warmup: -1
  num_epochs: 25
  pretrain_epochs: 3
  batch_size: 64
  resume: 1
  seed: 1111
  cuda: True
  log_interval: 100
  cycle: 500
  vocab:
    vocab_size: 10000
  model:
    batch_size: 64
    dropout: 0.2
    dim_emb: 32
    lr: 0.001
    beta: 0.1
    max_grad_norm: 5
    noise: '0,0.2,0,4'
    encoder:
      dim_h: 64
      dim_emb: 32 
      nlayers: 2
      dropout: 0.2
    form: 
      n_classes: 5
      lr: 0.001
      dim_emb: 8
      dim_z: 16
      dim_clf_z: 16
      dim_d: 32
      dropout: 0.2
      max_grad_norm: 5
    content: 
      dim_z: 16
      dim_clf_z: 16
      dim_d: 32
      n_labels: 8
      lr: 0.001
      dim_emb: 32
      dim_h: 64
      nlayers: 2
      dropout: 0.2
      max_grad_norm: 5
    decoder:
      dim_emb: 32
      dim_h: 64
      dim_z: 24
      nlayers: 2
      dropout: 0.2
      tf_ratio: 0.5
all:
  common:
    type: 'disae'
    data: 'data/personage-nlg/labelled'
    save_dir: 'debug_run'
  model:
    f_adv: 1
    c_mot: 1
      